package services

import (
	"terraform-provider-microsoft365wp/workplace/generic"
	"terraform-provider-microsoft365wp/workplace/wpschema/wpdefaultvalue"
	"terraform-provider-microsoft365wp/workplace/wpschema/wpplanmodifier"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	AzureAdWindowsAutopilotDeploymentProfileResource = generic.GenericResource{
		TypeNameSuffix: "azure_ad_windows_autopilot_deployment_profile",
		SpecificSchema: azureAdWindowsAutopilotDeploymentProfileResourceSchema,
		AccessParams: generic.AccessParams{
			BaseUri:                    "/deviceManagement/windowsAutopilotDeploymentProfiles",
			TerraformToGraphMiddleware: azureAdWindowsAutopilotDeploymentProfileTerraformToGraphMiddleware,
		},
	}

	AzureAdWindowsAutopilotDeploymentProfileSingularDataSource = generic.CreateGenericDataSourceSingularFromResource(
		&AzureAdWindowsAutopilotDeploymentProfileResource)

	AzureAdWindowsAutopilotDeploymentProfilePluralDataSource = generic.CreateGenericDataSourcePluralFromSingular(
		&AzureAdWindowsAutopilotDeploymentProfileSingularDataSource, "")
)

func azureAdWindowsAutopilotDeploymentProfileTerraformToGraphMiddleware(params generic.TerraformToGraphMiddlewareParams) generic.TerraformToGraphMiddlewareReturns {
	params.RawVal["@odata.type"] = "#microsoft.graph.azureADWindowsAutopilotDeploymentProfile"
	return nil
}

var (
	AzureAdWindowsAutopilotDeploymentProfileAssignmentResource           = GetAssignmentChildResource(&AzureAdWindowsAutopilotDeploymentProfileResource, true)
	AzureAdWindowsAutopilotDeploymentProfileAssignmentSingularDataSource = generic.CreateGenericDataSourceSingularFromResource(&AzureAdWindowsAutopilotDeploymentProfileAssignmentResource)
	AzureAdWindowsAutopilotDeploymentProfileAssignmentPluralDataSource   = generic.CreateGenericDataSourcePluralFromSingular(&AzureAdWindowsAutopilotDeploymentProfileAssignmentSingularDataSource, "")
)

var azureAdWindowsAutopilotDeploymentProfileResourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{ // azureADWindowsAutopilotDeploymentProfile
		"id": schema.StringAttribute{
			Computed:      true,
			PlanModifiers: []planmodifier.String{wpplanmodifier.StringUseStateForUnknown()},
		},
		"created_date_time": schema.StringAttribute{
			Computed:            true,
			PlanModifiers:       []planmodifier.String{wpplanmodifier.StringUseStateForUnknown()},
			MarkdownDescription: `The date and time of when the deployment profile was created. The value cannot be modified and is automatically populated when the profile was created. The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported. Read-Only.`,
		},
		"description": schema.StringAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("")},
			Computed:            true,
			MarkdownDescription: `A description of the deployment profile. Max allowed length is 1500 chars. Supports: $select, $top, $skip, $orderBy. $Search and $filter are not supported.`,
		},
		"device_name_template": schema.StringAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("")},
			Computed:            true,
			MarkdownDescription: `The template used to name the Autopilot device. This can be a custom text and can also contain either the serial number of the device, or a randomly generated number. The total length of the text generated by the template can be no more than 15 characters. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"device_type": schema.StringAttribute{
			Optional: true,
			Validators: []validator.String{
				stringvalidator.OneOf("windowsPc", "holoLens", "surfaceHub2", "surfaceHub2S", "virtualMachine", "unknownFutureValue"),
			},
			PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("windowsPc")},
			Computed:            true,
			MarkdownDescription: `The Windows device type that this profile is applicable to. Possible values include windowsPc, holoLens, and virtualMachine. The default is windowsPc. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"display_name": schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `The display name of the deployment profile. Max allowed length is 200 chars. Returned by default. Supports: $select, $top, $skip, $orderby. $Search and $filter are not supported.`,
		},
		"enrollment_status_screen_settings": schema.SingleNestedAttribute{
			Optional: true,
			Attributes: map[string]schema.Attribute{ // windowsEnrollmentStatusScreenSettings
				"allow_device_use_before_profile_and_app_install_complete": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: `Allow or block user to use device before profile and app installation complete`,
				},
				"allow_device_use_on_install_failure": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: `Allow the user to continue using the device on installation failure`,
				},
				"allow_log_collection_on_install_failure": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: `Allow or block log collection on installation failure`,
				},
				"block_device_setup_retry_by_user": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: `Allow the user to retry the setup on installation failure`,
				},
				"custom_error_message": schema.StringAttribute{
					Optional:            true,
					MarkdownDescription: `Set custom error message to show upon installation failure`,
				},
				"hide_installation_progress": schema.BoolAttribute{
					Required:            true,
					MarkdownDescription: `Show or hide installation progress to user`,
				},
				"install_progress_timeout_in_minutes": schema.Int64Attribute{
					Optional:            true,
					MarkdownDescription: `Set installation progress timeout in minutes`,
				},
			},
			MarkdownDescription: `Enrollment status screen setting / Enrollment status screen setting`,
		},
		"hardware_hash_extraction_enabled": schema.BoolAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
			Computed:            true,
			MarkdownDescription: `Indicates whether the profile supports the extraction of hardware hash values and registration of the device into Windows Autopilot. When TRUE, indicates if hardware extraction and Windows Autopilot registration will happen on the next successful check-in. When FALSE, hardware hash extraction and Windows Autopilot registration will not happen. Default value is FALSE. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"last_modified_date_time": schema.StringAttribute{
			Computed:            true,
			PlanModifiers:       []planmodifier.String{wpplanmodifier.StringUseStateForUnknown()},
			MarkdownDescription: `The date and time of when the deployment profile was last modified. The value cannot be updated manually and is automatically populated when any changes are made to the profile. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported Read-Only.`,
		},
		"locale": schema.StringAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("os-default")},
			Computed:            true,
			MarkdownDescription: `The locale (language) to be used when configuring the device. E.g. en-US. The default value is os-default. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"management_service_app_id": schema.StringAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("")},
			Computed:            true,
			MarkdownDescription: `The Entra management service App ID which gets used during client device-based enrollment discovery. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"out_of_box_experience_setting": schema.SingleNestedAttribute{
			Optional: true,
			Attributes: map[string]schema.Attribute{ // outOfBoxExperienceSetting
				"device_usage_type": schema.StringAttribute{
					Optional: true,
					Validators: []validator.String{
						stringvalidator.OneOf("singleUser", "shared", "unknownFutureValue"),
					},
					PlanModifiers:       []planmodifier.String{wpdefaultvalue.StringDefaultValue("singleUser")},
					Computed:            true,
					MarkdownDescription: `The Entra join authentication type. Possible values are singleUser and shared. The default is singleUser.`,
				},
				"escape_link_hidden": schema.BoolAttribute{
					Optional:            true,
					PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
					Computed:            true,
					MarkdownDescription: `When TRUE, the link that allows user to start over with a different account on company sign-in is hidden. When false, the link that allows user to start over with a different account on company sign-in is available. Default value is FALSE.`,
				},
				"eula_hidden": schema.BoolAttribute{
					Optional:            true,
					PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
					Computed:            true,
					MarkdownDescription: `When TRUE, EULA is hidden to the end user during OOBE. When FALSE, EULA is shown to the end user during OOBE. Default value is FALSE.`,
				},
				"keyboard_selection_page_skipped": schema.BoolAttribute{
					Optional:            true,
					PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
					Computed:            true,
					MarkdownDescription: `When TRUE, the keyboard selection page is hidden to the end user during OOBE if Language and Region are set. When FALSE, the keyboard selection page is skipped during OOBE.`,
				},
				"privacy_settings_hidden": schema.BoolAttribute{
					Optional:            true,
					PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
					Computed:            true,
					MarkdownDescription: `When TRUE, privacy settings is hidden to the end user during OOBE. When FALSE, privacy settings is shown to the end user during OOBE. Default value is FALSE.`,
				},
				"user_type": schema.StringAttribute{
					Optional: true,
					Validators: []validator.String{
						stringvalidator.OneOf("administrator", "standard", "unknownFutureValue"),
					},
					PlanModifiers: []planmodifier.String{wpdefaultvalue.StringDefaultValue("administrator")},
					Computed:      true,
					MarkdownDescription: `The type of user. Possible values are administrator and standard. Default value is administrator. Yes No
`,
				},
			},
			PlanModifiers:       []planmodifier.Object{wpdefaultvalue.ObjectDefaultValueEmpty()},
			Computed:            true,
			MarkdownDescription: `The Windows Autopilot Deployment Profile settings used by the device for the out-of-box experience. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported. / The Windows Autopilot Deployment Profile settings used by the device for the out-of-box experience. Supports: $select, $top, $skip. $Search, $orderBy and $filter are not supported.`,
		},
		"preprovisioning_allowed": schema.BoolAttribute{
			Optional:            true,
			PlanModifiers:       []planmodifier.Bool{wpdefaultvalue.BoolDefaultValue(false)},
			Computed:            true,
			MarkdownDescription: `Indicates whether the user is allowed to use Windows Autopilot for pre-provisioned deployment mode during Out of Box experience (OOBE). When TRUE, indicates that Windows Autopilot for pre-provisioned deployment mode for OOBE is allowed to be used. When false, Windows Autopilot for pre-provisioned deployment mode for OOBE is not allowed. The default is FALSE.`,
		},
		"role_scope_tag_ids": schema.SetAttribute{
			ElementType:         types.StringType,
			Optional:            true,
			PlanModifiers:       []planmodifier.Set{wpdefaultvalue.SetDefaultValue([]any{"0"})},
			Computed:            true,
			MarkdownDescription: `List of role scope tags for the deployment profile. `,
		},
	},
	MarkdownDescription: `Windows Autopilot Deployment Profile`,
}
