// Code generated by edmx2go; DO NOT EDIT.

package services

import (
	"terraform-provider-microsoft365wp/workplace/generic"
	"terraform-provider-microsoft365wp/workplace/wpschema/wpplanmodifier"
	"terraform-provider-microsoft365wp/workplace/wpschema/wpvalidator"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	IpApplicationSegmentResource = generic.GenericResource{
		TypeNameSuffix: "ip_application_segment",
		SpecificSchema: ipApplicationSegmentResourceSchema,
		AccessParams: generic.AccessParams{
			BaseUri: "/applications",
			ParentEntities: generic.ParentEntities{
				{
					ParentIdField: path.Root("application_id"),
					UriSuffix:     "onPremisesPublishing/segmentsConfiguration/microsoft.graph.ipSegmentConfiguration/applicationSegments",
				},
			},
			WriteOptions: generic.WriteOptions{
				SerializeWrites:   true,
				SerialWritesDelay: time.Second * 5,
			},
		},
	}

	IpApplicationSegmentSingularDataSource = generic.CreateGenericDataSourceSingularFromResource(
		&IpApplicationSegmentResource)

	IpApplicationSegmentPluralDataSource = generic.CreateGenericDataSourcePluralFromResource(
		&IpApplicationSegmentResource, "")
)

var ipApplicationSegmentResourceSchema = schema.Schema{
	Attributes: map[string]schema.Attribute{ // ipApplicationSegment
		"application_id": schema.StringAttribute{
			Required:            true,
			PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			MarkdownDescription: "_Provider_ Note: ID of the application that this application segment belongs to. Required.",
		},
		"id": schema.StringAttribute{
			Computed:            true,
			PlanModifiers:       []planmodifier.String{wpplanmodifier.StringUseStateForUnknown()},
			MarkdownDescription: "Identifier for the application segment.",
		},
		"destination_host": schema.StringAttribute{
			Required:            true,
			MarkdownDescription: "Either the IP address, IP range, or FQDN of the **applicationSegment**, with or without wildcards.",
		},
		"destination_type": schema.StringAttribute{
			Required: true,
			Validators: []validator.String{
				stringvalidator.OneOf("ip", "ipRange", "ipRangeCidr", "fqdn", "dnsSuffix", "unknownFutureValue", "servicePrincipalName"),
			},
			MarkdownDescription: "The possible values are: `ip`, `ipRange`, `ipRangeCidr`, `fqdn`, `dnsSuffix`, `unknownFutureValue`, `servicePrincipalName`. <br/> _Provider_ allowed values are: `ip`, `ipRange`, `ipRangeCidr`, `fqdn`, `dnsSuffix`, `unknownFutureValue`, `servicePrincipalName`.",
		},
		"ports": schema.SetAttribute{
			ElementType:         types.StringType,
			Required:            true,
			MarkdownDescription: "List of ports supported for the application segment.",
		},
		"protocol": schema.StringAttribute{
			Required: true,
			Validators: []validator.String{
				wpvalidator.FlagEnumValues("tcp", "udp", "unknownFutureValue"),
			},
			MarkdownDescription: "Indicates the protocol of the network traffic acquired for the application segment. <br/> _Provider_ allowed values are: `tcp`, `udp`, `unknownFutureValue`.",
		},
	},
	MarkdownDescription: "Represents the segment configurations that are allowed for an **on-premises nonweb application** published through Microsoft Entra application proxy and accessed via non-HTTP protocols. <br/> Also see [Microsoft docs for ipApplicationSegment](https://learn.microsoft.com/en-us/graph/api/resources/ipapplicationsegment?view=graph-rest-beta).\n\n_Provider_ Note: To import this resource, an ID consisting of `application_id` and `id` being joined by a forward slash (`/`) must be used. ||| MS Graph: Applications",
}
